CREATE TABLE `db-weather`.weather_cities (
	ID varchar(100) NOT NULL,
	CITY varchar(100) NOT NULL,
	NUMBER_REQUEST INT DEFAULT 0 NULL,
	LAST_REQUEST DATETIME NULL,
	REQUEST TEXT NULL,
	CONSTRAINT WEATHER_CITIES_PK PRIMARY KEY (ID),
	CONSTRAINT WEATHER_CITIES_UN UNIQUE KEY (CITY)
)